<?php

declare(strict_types=1);

namespace Platform\Bundle\MBE\MBE4\SDK\Enum;

enum TransactionStatus: int
{
    case UNKNOWN = -1;
    case CREATED = 0;
    case TAN_SMS_SENT = 1;
    case TAN_WAITING_FOR_CALLBACK = 2;
    case TAN_RECEIVED = 3;
    case AUTHORIZATION_CREATED = 4;
    case AUTHORIZATION_WAITING_FOR_CALLBACK = 5;
    case AUTHORIZED = 6;
    case CAPTURE_CREATED = 7;
    case CAPTURE_WAITING_FOR_CALLBACK = 8;
    case CAPTURED = 9;
    case TERMINATE_CREATED = 10;
    case TERMINATE_WAITING_FOR_CALLBACK = 11;
    case TERMINATED = 12;
    case REFUND_CREATED = 13;
    case REFUND_WAITING_FOR_CALLBACK = 14;
    case REFUNDED = 15;
    case DIRECTCAPTURE_CREATED = 16;
    case DIRECTCAPTURE_WAITING_FOR_CALLBACK = 17;
    case DIRECTCAPTURED = 18;
    case DIRECTCAPTURE_ONETIMEPIN_CREATED = 19;
    case DIRECTCAPTURE_ONETIMEPIN_TAN_REQUESTED = 20;
    case DIRECTCAPTURE_ONETIMEPIN_TAN_SENT = 21;
    case DIRECTCAPTURE_ONETIMEPIN_TANRECEIVED = 22;
    case DIRECTCAPTURE_ONETIMEPIN_WAITING_FOR_CALLBACK = 23;
    case AUTHORIZE_ONETIMEPIN_CREATED = 24;
    case AUTHORIZE_ONETIMEPIN_TAN_REQUESTED = 25;
    case AUTHORIZE_ONETIMEPIN_TAN_SENT = 26;
    case AUTHORIZE_ONETIMEPIN_TAN_RECEIVED = 27;
    case AUTHORIZE_ONETIMEPIN_WAITING_FOR_CALLBACK = 28;
    case SUBSCRIPTION_SETUP_ONETIMEPIIN_CREATED = 29;
    case SUBSCRIPTION_SETUP_ONETIMEPIIN_TAN_REQUESTED = 30;
    case SUBSCRIPTION_SETUP_ONETIMEPIIN_TAN_SENT = 31;
    case SUBSCRIPTION_SETUP_ONETIMEPIIN_TAN_RECEIVED = 32;
    case SUBSCRIPTION_SETUP_ONETIMEPIIN_WAITING_FOR_CALLBACK = 33;
    case SUBSCRIPTION_SETUP_CREATED = 34;
    case SUBSCRIPTION_SETUP_WAITING_FOR_CALLBACK = 35;
    case SUBSCRIPTION_TERMINATE_CREATED = 36;
    case SUBSCRIPTION_TERMINATE_WAITING_FOR_CALLBACK = 37;
    case SUBSCRIPTION_TERMINATED = 38;
    case WEBFLOW_CREATED = 201;
    case WEBFLOW_INITIALIZED = 202;
    case WEBFLOW_AUTHORIZED = 203;
    case WEBFLOW_CAPTURED = 204;
    case WEBFLOW_REFUNDED = 205;
    case WEBFLOW_CHARGEBACK = 206;
    case WEBFLOW_TERMINATED = 299;
}
